config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  resources :phones

end

app/models/phone.rb
class Phone < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  before_action :set_phone, only: [:show, :edit, :update, :destroy]

  # GET /phones
  # GET /phones.json
  def index
    @phones = Phone.all
  end

  # GET /phones/1
  # GET /phones/1.json
  def show
  end

  # GET /phones/new
  def new
    @phone = Phone.new
  end

  # GET /phones/1/edit
  def edit
  end

  # POST /phones
  # POST /phones.json
  def create
    @phone = Phone.new(phone_params)

    respond_to do |format|
      if @phone.save
        format.html { redirect_to @phone, notice: 'Phone was successfully created.' }
        format.json { render :show, status: :created, location: @phone }
      else
        format.html { render :new }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phones/1
  # PATCH/PUT /phones/1.json
  def update
    respond_to do |format|
      if @phone.update(phone_params)
        format.html { redirect_to @phone, notice: 'Phone was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone }
      else
        format.html { render :edit }
        format.json { render json: @phone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phones/1
  # DELETE /phones/1.json
  def destroy
    @phone.destroy
    respond_to do |format|
      format.html { redirect_to phones_url, notice: 'Phone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone
      @phone = Phone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_params
      params.require(:phone).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phoneapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">The Idea app</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/ideas">Ideas</a></li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>


  <footer>
    <div class="container">
      Rails Girls 2015
    </div>
  </footer>
  <script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>

app/views/pages/info.html.erb
<div class="container">
    <div class="row">
<br>
<br>
    	<div class="span3 well">
        <center>
        <a href="#aboutModal" data-toggle="modal"><img src="http://img2.timeinc.net/people/i/2014/database/140831/justin-bieber-300.jpg" name="aboutme" width="140" height="140" class="img-circle"></a>
         <h3>Joe Sixpack</h3>
         <em>click my face for more</em>
         <p>By the way,<br><a target="_blank" href="http://bootsnipp.com/TXTCLASS/snippets/25zz">there's a fresh 3.1.0 version ready</a></p>
			</center>
            <div class="modal hide" id="aboutModal">
			    <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal">✕</button>
			        <h3>About Joe</h3>
			    </div>
			        <div class="modal-body" style="text-align:center;">
			        <div class="row-fluid">
			            <div class="span10 offset1">
			                <div id="modalTab">
			                    <div class="tab-content">
			                        <div class="tab-pane active" id="about">
    <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRbezqZpEuwGSvitKy3wrwnth5kysKdRqBW54cAszm_wiutku3R" name="aboutme" width="140" height="140" border="0" class="img-circle"></a>
      <h3 class="media-heading">Joe Sixpack <small> USA</small></h3>
                <span><strong>Skills: </strong></span>
                <span class="label label-warning">HTML5/CSS</span>
                <span class="label label-info">Adobe CS 5.5</span>
                <span class="label label-info">Microsoft Office</span>
                <span class="label label-success">Windows XP, Vista, 7</span>
    </center>
    <hr>
    <center>
    <p class="text-left"><strong>Bio: </strong><br>
     Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sem dui, tempor sit amet commodo a, vulputate vel tellus.</p>
      <br>
      </center>
      </div>
	</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</div>

app/views/phones/_form.html.erb
<%= form_for(@phone) do |f| %>
  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phone.errors.count, "error") %> prohibited this phone from being saved:</h2>

      <ul>
      <% @phone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phones/edit.html.erb
<h1>Editing phone</h1>

<%= render 'form' %>

<%= link_to 'Show', @phone %> |
<%= link_to 'Back', phones_path %>

app/views/phones/index.html.erb
<h1>Listing phones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phones.each do |phone| %>
      <tr>
        <td><%= phone.name %></td>
        <td><%= phone.description %></td>
        <td><%= phone.picture %></td>
        <td><%= link_to 'Show', phone %></td>
        <td><%= link_to 'Edit', edit_phone_path(phone) %></td>
        <td><%= link_to 'Destroy', phone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone', new_phone_path %>

app/views/phones/new.html.erb
<h1>New phone</h1>

<%= render 'form' %>

<%= link_to 'Back', phones_path %>

app/views/phones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @phone.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @phone.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @phone.picture %>
</p>

<%= link_to 'Edit', edit_phone_path(@phone) %> |
<%= link_to 'Back', phones_path %>